#!/usr/bin/python3
<<<<<<< HEAD
"""
Coontains class BaseModel
"""
=======
'''
    This module defines the BaseModel class
    '''
    from os import getenv
    import uuid
    from datetime import datetime
    import models
    from sqlalchemy import Column, String, Integer, DateTime
    from sqlalchemy.ext.declarative import declarative_base
>>>>>>> 6e7511263a25b22fb7180a2a53d1daa63c24a997


    Base = declarative_base()


    class BaseModel:
            '''
                    Base class for other classes to be used for the duration.
                        '''
                            id = Column(String(60), nullable=False, primary_key=True)
                                created_at = Column(DateTime, default=datetime.utcnow(), nullable=False)
                                    updated_at = Column(DateTime, default=datetime.utcnow(), nullable=False)

                                        def __init__(self, *args, **kwargs):
                                                '''
                                                            Initialize public instance attributes.
                                                                    '''
                                                                            if (len(kwargs) == 0):
                                                                                        self.id = str(uuid.uuid4())
                                                                                                    self.created_at = datetime.now()
                                                                                                                self.updated_at = datetime.now()
                                                                                                                        else:
                                                                                                                                    if kwargs.get("created_at"):
                                                                                                                                                    kwargs["created_at"] = datetime.strptime(
                                                                                                                                                                        kwargs["created_at"], "%Y-%m-%dT%H:%M:%S.%f")
                                                                                                                                                                                    else:
                                                                                                                                                                                                    self.created_at = datetime.now()
                                                                                                                                                                                                                if kwargs.get("created_at"):
                                                                                                                                                                                                                                kwargs["updated_at"] = datetime.strptime(
                                                                                                                                                                                                                                                    kwargs["updated_at"], "%Y-%m-%dT%H:%M:%S.%f")
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                self.updated_at = datetime.now()
                                                                                                                                                                                                                                                                                            for key, val in kwargs.items():
                                                                                                                                                                                                                                                                                                            if "__class__" not in key:
                                                                                                                                                                                                                                                                                                                                setattr(self, key, val)
                                                                                                                                                                                                                                                                                                                                            if not self.id:
                                                                                                                                                                                                                                                                                                                                                            self.id = str(uuid.uuid4())

                                                                                                                                                                                                                                                                                                                                                                def __str__(self):
                                                                                                                                                                                                                                                                                                                                                                        '''
                                                                                                                                                                                                                                                                                                                                                                                    Return string representation of BaseModel class
                                                                                                                                                                                                                                                                                                                                                                                            '''
                                                                                                                                                                                                                                                                                                                                                                                                    return ("[{}] ({}) {}".format(self.__class__.__name__,
                                                                                                                                                                                                                                                                                                                                                                                                                                          self.id, self.__dict__))

                                                                                                                                                                                                                                                                                                                                                                                                                                              def __repr__(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                      '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Return string representation of BaseModel class
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return ("[{}] ({}) {}".format(self.__class__.__name__,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.id, self.__dict__))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def save(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Update the updated_at attribute with new.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.updated_at = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        models.storage.new(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                models.storage.save()

<<<<<<< HEAD
    def to_dict(self, save_check=False):
        """returns a dictionary containing all keys/values of the instance"""
        new_dict = self.__dict__.copy()
        if "created_at" in new_dict:
            new_dict["created_at"] = new_dict["created_at"].strftime(time)
        if "updated_at" in new_dict:
            new_dict["updated_at"] = new_dict["updated_at"].strftime(time)
        new_dict["__class__"] = self.__class__.__name__
        if "_sa_instance_state" in new_dict:
            del new_dict["_sa_instance_state"]
        if "password" in new_dict and save_check is False:
            del new_dict["password"]
        return new_dict
=======
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def to_dict(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Return dictionary representation of BaseModel class.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cp_dct = dict(self.__dict__)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cp_dct['__class__'] = self.__class__.__name__
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cp_dct['updated_at'] = self.updated_at.strftime("%Y-%m-%dT%H:%M:%S.%f")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cp_dct['created_at'] = self.created_at.strftime("%Y-%m-%dT%H:%M:%S.%f")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if hasattr(self, "_sa_instance_state"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    del cp_dct["_sa_instance_state"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (cp_dct)
>>>>>>> 6e7511263a25b22fb7180a2a53d1daa63c24a997

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def delete(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Deletes an object
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            '''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    models.storage.delete(self)
